---
- name: Deploy Docker container engine
  package: name=docker state=installed

- name: Restart and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker
